### ISSUE TITLE
No parameter-level intellisense comments

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/gcloud-dotnet#182]
The XML doc comments for the Pub/Sub API (and I assume all other GRPC-based ones) only contains descriptions of the methods, but not the specific parameters.

It looks like the description exists, it is just a matter of wiring it into our XML doc comments.
https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/pull#path-parameters

![image](https://cloud.githubusercontent.com/assets/4029847/15590715/e7a48090-234d-11e6-96a2-d4b3bb45a1c3.png)

**Comment by jskeet** [comment]
This is due to https://github.com/googleapis/toolkit/issues/152 - if you look at the [method declaration](https://github.com/GoogleCloudPlatform/gcloud-dotnet/blob/master/src/Google.Pubsub.V1/SubscriberClient.cs#L1111) you'll see `return_immediately` instead of `returnImmediately`.

You should get Intellisense for `subscription` as that's only one word.

**Comment by jskeet** [comment]
Assigning to Chris to verify when the generator has been fixed.
