### ISSUE TITLE
Carefully consider the overloads we want for DownloadObject

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#21]
There are four choices the user can make for a download call:

- The source, which may be specified as an Object or a bucket/name pair
- The target, which may be specified a local file name or a Stream
- Sync/async
- Whether or not there are options (including progress reporting)

That naturally leads to 16 overloads (or two pairs of 8 overloads, in that the sync and async methods have different names). This feels like overkill.

We can avoid overloads for the first two choices if we say that it's *always* to a Stream (forcing callers to call File.OpenWrite themselves) or force the bucket/sourceName to be specified (forcing callers to use obj.Bucket, obj.Name if they have an Object already). For the latter case, we could force callers to *create* an Object if they don't have one already instead. Both cases feel a little odd to me.

I'll probably code up all 16 methods for the moment but without documentation, and we can pick which ones to cull.

**Comment by jskeet** [comment]
Oh, and if we ever have the ability to get a return value of a stream, that's presumably another set of methods (although not a doubling...)

**Comment by SurferJeffAtGoogle** [comment]
Have you considered the fluent pattern?
service.Download().withSource(...).withTarget(...).withOptions(...).ExecuteAsync()...

Actually, I think 16 overloads are better.

**Comment by jskeet** [comment]
// cc @ivannaranjo @mmdriley @chrsmith @csells

**Comment by ivannaranjo** [comment]
I would say that the target being a stream is a good compromise, having the user open the file is probably best since they know exactly how to do so, that is, permissions, whether to overwrite, append, etc, etc... So we could remove that overload right there.

As for the source, yes I think that we will have to bite the bullet and have both the object and one accepting the bucket and name, since it is going to be quite common to get objects, from listing them, and create the names directly, programmatically. I would like us to have also objects paths like `gs://bucket/name/of/object.jpg` similar to what `gsutil` allows, but that is probably a completely different discussion, and this would also add an extra overload :).

options/not-options I think are also necessary, this is where perhaps having default arguments might help? If we were to deviate from the TAP pattern perhaps? 

Async/async I think are necessary and unavoidable. Although this said, one could just built it on the other.

**Comment by csells** [comment]
What do the .NET file operations do here?

**Comment by chrsmith** [comment]
@SurferJeffAtGoogle A fluent pattern would help in this situation, but I don't believe that is idiomatic C#. e.g. I don't think there are any BCL classes that use a fluent approach.

@jskeet There is precident for having a method with a bazillion overloads. e.g. `Console.WriteLine` or `MessageBox.Show`. But I don't think we should be super-liberal in creating overloads. Why not just keep the simple case simple, i.e. don't allow custom options or an async variant for the most common download-to-file case? e.g.:

- void DownloadFile(GcsObject gcsObject, string filePath)
- Stream Download(GcsObject gcsObject, GcsOptions)
- Task<Stream> DownloadAsync(GcsObject gcsObject, GcsOptions)

This way the common case is simple and more advanced users can use the Async/Option-enabled variants to create some middle ground as needed.

Feel free to shoot this down out of principle. But I personally would optimize for reducing the number of methods we expose in total.

**Comment by jskeet** [comment]
Unfortunately we can't currently have a method to return a stream to read from - we'd like to, but the download functionality in the core library isn't based on that idea, and we should add it *there* rather than in a wrapper.

In terms of asyncness - it would be pretty odd *not* to provide an async option these days.

**Comment by mmdriley** [comment]
We can always add more overloads later. :)

**Comment by ivannaranjo** [comment]
But we can't remove so we have to think about this carefully. I would agree that erring on the side of fewer overloads is the way to go. Later we can add more based on usage, and specifically issues/complaints.

**Comment by jskeet** [comment]
Agree that we can't remove overloads after 1.0, although we've got plenty of opportunity for feedback before that. We'll want to get feedback on using optional parameters to remove a bunch of overloads too.

**Comment by jskeet** [comment]
I think we're reasonably happy with where we are now.
